### PR TITLE
Add Weaknesses command

### PR DESCRIPTION
**Pull request by miguel-felix1**
## Description

Added a command to both the Dex and Pokemon detail view to display the currently selected Pokemon's weaknesses

## Screencast

https://github.com/anhthang/raycast-pokedex/assets/87712174/fac97232-7ea3-4546-9ac4-cc7675d78190

## Todo/Fix
[ ] Forms are not displayed (add a dropdown)
[ ] Takes a long time to calculate weaknesses and display them
[ ] Tried to add a debouncer to mitigate scrolling too fast breaking the extension (still not 100%)
[ ] Design is a bit ugly/not in line with the current extension

Hey @anhthang ! I've been working on it on my free time and this is what I came up with, I'm still kinda new to this and I wanted to make the command available to use from anywhere (hence why I display a list with every Pokemon available), so that we could in theory add a new standalone command akin to the moves/abilities while still being able to call it from the main views, let me know what you think and feel free to change it however you like !

### CODE REVIEW

**Comment by anhthang** [comment]
Hi @miguel-felix1 👋

The design for the new standalone command looks great!  Just a thought -  if we're keeping the quick jump from Pokemon details, perhaps we could create a different view for it that maintains consistency with the current view (using simpler details)

If possible, please also sync the Raycast extension fixes to this PR.

**Comment by miguel-felix1** [comment]
Yup, forgot to sync the changes from the last PR, done ! And yeah can definitely work on a simpler detail view for the weaknesses if we are coming from the details view of a specific Pokemon, and if we come from the dex should we keep the list view ? Or also use the detail view and repurpose the list view with all the Pokemon to a brand new command instead ?

**Comment by anhthang** [comment]
I like your design for the new command! Just keep it if you come from the dex.

To maintain consistency with the existing Pokedex grid, I'd prefer to keep the grid size the same. For a more compact layout, you can add new config to change size. This allows you and others to choose smalleritems.

**Comment by anhthang** [comment]
@miguel-felix1 you're still working on it, right? I don't see the new command when checkout the PR

**Comment by miguel-felix1** [comment]
> @miguel-felix1 you're still working on it, right? I don't see the new command when checkout the PR

Yeah yeah @anhthang I'm still working on it on my free time 😅 this weekend I didn't touch it tho, but yeah I didn't add a new command, it's actually an action on the dex view and detail view ! 

Ah and the grid size I changed it on my own fork, I didn't commit that change, I just prefer to show more columns, but we can definitely make that a preference setting !

**Comment by anhthang** [comment]
You can change it to ready for review once done and I will check it again

**Pull request merged**
